import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.agmeo.com/sign-in');
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.getByRole('textbox', { name: 'E-Mail-Adresse' }).click();
  await page.getByRole('textbox', { name: 'E-Mail-Adresse' }).fill('razvancostache97@gmail.com');
  await page.getByRole('button', { name: 'Weiter' }).click();
  await page.getByRole('textbox', { name: 'Passwort' }).click();
  await page.getByRole('textbox', { name: 'Passwort' }).fill('Agvolution2025');
  await page.getByRole('textbox', { name: 'Passwort' }).press('Enter');
 // await page.getByRole('button', { name: 'Weiter' }).click();
  await page.getByRole('button', { name: 'Open user button' }).click();
 // await page.getByText('razvancostache97@gmail.com').click();
  await page.getByLabel('User button popover').getByRole('img', { name: '\'s logo' }).click();
  await page.getByLabel('User button popover').getByRole('img', { name: '\'s logo' }).click();
  await page.getByText('razvancostache97@gmail.com').click();
  await page.getByRole('menuitem', { name: 'Konto verwalten' }).click();
  await page.getByRole('button', { name: 'Sprache' }).click();
  await page.getByRole('button', { name: 'Deutsch' }).click();
  await page.getByRole('menuitem', { name: 'English' }).click();
  await page.getByRole('button', { name: 'Close modal' }).click();
  /*await page.getByRole('table').getByRole('button', { name: 'Choose action' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('heading', { name: 'Fields' }).click();
  await page.locator('#title-portal div').filter({ hasText: /^Fields$/ }).locator('svg').click();
  await page.getByRole('link').filter({ hasText: 'Culture' }).click();
  await page.getByRole('combobox', { name: 'Kultur auswählen...' }).click();
  await page.getByRole('link').filter({ hasText: /^Map$/ }).click();
  await page.getByRole('button', { name: 'Expand sidebar' }).click();
  await page.getByRole('button', { name: 'Farm' }).click();
  await page.getByRole('menuitem', { name: 'Create new farm' }).click();
  await page.getByRole('textbox', { name: 'Zum Beispiel: Lindenhof Klein' }).click();
  await page.getByRole('textbox', { name: 'Zum Beispiel: Lindenhof Klein' }).fill('TestFarm');
  await page.getByRole('button', { name: 'Create farm' }).click();
  await page.getByRole('button', { name: 'Fruchtfolgen anlegen' }).click();
  await page.getByRole('textbox', { name: 'Name of the crop rotation *' }).click();
  await page.getByRole('textbox', { name: 'Name of the crop rotation *' }).click();
  await page.getByRole('textbox', { name: 'Name of the crop rotation *' }).fill('TestRotation');
  await page.getByRole('button', { name: 'Add another crop' }).click();
 // await page.locator('#headlessui-control-_r_4t_').selectOption('sunflower');
  //await page.locator('#headlessui-control-_r_50_').selectOption('22df1307-d395-473d-907b-cc7c40b25a69');
  await page.getByRole('button', { name: 'Save crop rotations' }).click();
  await page.getByRole('button', { name: 'Skip' }).click();
  await page.getByRole('button', { name: 'TestFarm' }).click();
  await page.getByRole('menuitem', { name: 'Farm 2' }).click();
  await page.getByRole('button', { name: 'Farm' }).click();
  await page.getByRole('menuitem', { name: 'TestFarm' }).click();*/
});